// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzhekyabosnirvdpgebv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6aGVreWFib3NuaXJ2ZHBnZWJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MTA4MzEsImV4cCI6MjA1ODE4NjgzMX0.CiV3eMnwFWu-9vwSh9EpLNgUTIvNqJdy55Z-hsu0Kfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);